// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: corpc_option.proto

#ifndef PROTOBUF_corpc_5foption_2eproto__INCLUDED
#define PROTOBUF_corpc_5foption_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "google/protobuf/descriptor.pb.h"
// @@protoc_insertion_point(includes)

namespace corpc {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_corpc_5foption_2eproto();
void protobuf_AssignDesc_corpc_5foption_2eproto();
void protobuf_ShutdownFile_corpc_5foption_2eproto();


// ===================================================================


// ===================================================================

static const int kGlobalServiceIdFieldNumber = 10000;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint32 >, 13, false >
  global_service_id;
static const int kNeedCoroutineFieldNumber = 10002;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  need_coroutine;

// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace corpc

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_corpc_5foption_2eproto__INCLUDED
