// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: corpc_thirdparty.proto

#ifndef PROTOBUF_corpc_5fthirdparty_2eproto__INCLUDED
#define PROTOBUF_corpc_5fthirdparty_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
#include "corpc_option.pb.h"
// @@protoc_insertion_point(includes)

namespace corpc {
namespace thirdparty {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_corpc_5fthirdparty_2eproto();
void protobuf_AssignDesc_corpc_5fthirdparty_2eproto();
void protobuf_ShutdownFile_corpc_5fthirdparty_2eproto();

class Handle;

// ===================================================================

class Handle : public ::google::protobuf::Message {
 public:
  Handle();
  virtual ~Handle();

  Handle(const Handle& from);

  inline Handle& operator=(const Handle& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Handle& default_instance();

  void Swap(Handle* other);

  // implements Message ----------------------------------------------

  Handle* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Handle& from);
  void MergeFrom(const Handle& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 handle = 1;
  inline bool has_handle() const;
  inline void clear_handle();
  static const int kHandleFieldNumber = 1;
  inline ::google::protobuf::uint64 handle() const;
  inline void set_handle(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:corpc.thirdparty.Handle)
 private:
  inline void set_has_handle();
  inline void clear_has_handle();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 handle_;
  friend void  protobuf_AddDesc_corpc_5fthirdparty_2eproto();
  friend void protobuf_AssignDesc_corpc_5fthirdparty_2eproto();
  friend void protobuf_ShutdownFile_corpc_5fthirdparty_2eproto();

  void InitAsDefaultInstance();
  static Handle* default_instance_;
};
// ===================================================================

class ThirdPartyService_Stub;

class ThirdPartyService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline ThirdPartyService() {};
 public:
  virtual ~ThirdPartyService();

  typedef ThirdPartyService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void take(::google::protobuf::RpcController* controller,
                       const ::corpc::Void* request,
                       ::corpc::thirdparty::Handle* response,
                       ::google::protobuf::Closure* done);
  virtual void put(::google::protobuf::RpcController* controller,
                       const ::corpc::thirdparty::Handle* request,
                       ::corpc::Void* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(ThirdPartyService);
};

class ThirdPartyService_Stub : public ThirdPartyService {
 public:
  ThirdPartyService_Stub(::google::protobuf::RpcChannel* channel);
  ThirdPartyService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~ThirdPartyService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements ThirdPartyService ------------------------------------------

  void take(::google::protobuf::RpcController* controller,
                       const ::corpc::Void* request,
                       ::corpc::thirdparty::Handle* response,
                       ::google::protobuf::Closure* done);
  void put(::google::protobuf::RpcController* controller,
                       const ::corpc::thirdparty::Handle* request,
                       ::corpc::Void* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(ThirdPartyService_Stub);
};


// ===================================================================


// ===================================================================

// Handle

// required uint64 handle = 1;
inline bool Handle::has_handle() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Handle::set_has_handle() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Handle::clear_has_handle() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Handle::clear_handle() {
  handle_ = GOOGLE_ULONGLONG(0);
  clear_has_handle();
}
inline ::google::protobuf::uint64 Handle::handle() const {
  // @@protoc_insertion_point(field_get:corpc.thirdparty.Handle.handle)
  return handle_;
}
inline void Handle::set_handle(::google::protobuf::uint64 value) {
  set_has_handle();
  handle_ = value;
  // @@protoc_insertion_point(field_set:corpc.thirdparty.Handle.handle)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace thirdparty
}  // namespace corpc

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_corpc_5fthirdparty_2eproto__INCLUDED
