// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: corpc_thirdparty.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "corpc_thirdparty.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace corpc {
namespace thirdparty {

namespace {

const ::google::protobuf::Descriptor* Handle_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Handle_reflection_ = NULL;
const ::google::protobuf::ServiceDescriptor* ThirdPartyService_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_corpc_5fthirdparty_2eproto() {
  protobuf_AddDesc_corpc_5fthirdparty_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "corpc_thirdparty.proto");
  GOOGLE_CHECK(file != NULL);
  Handle_descriptor_ = file->message_type(0);
  static const int Handle_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Handle, handle_),
  };
  Handle_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Handle_descriptor_,
      Handle::default_instance_,
      Handle_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Handle, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Handle, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Handle));
  ThirdPartyService_descriptor_ = file->service(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_corpc_5fthirdparty_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Handle_descriptor_, &Handle::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_corpc_5fthirdparty_2eproto() {
  delete Handle::default_instance_;
  delete Handle_reflection_;
}

void protobuf_AddDesc_corpc_5fthirdparty_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::corpc::protobuf_AddDesc_corpc_5foption_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026corpc_thirdparty.proto\022\020corpc.thirdpar"
    "ty\032\022corpc_option.proto\"\030\n\006Handle\022\016\n\006hand"
    "le\030\001 \002(\0042\202\001\n\021ThirdPartyService\0223\n\004take\022\013"
    ".corpc.Void\032\030.corpc.thirdparty.Handle\"\004\220"
    "\361\004\001\0222\n\003put\022\030.corpc.thirdparty.Handle\032\013.c"
    "orpc.Void\"\004\230\361\004\001\032\004\200\361\004\001B\003\200\001\001", 226);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "corpc_thirdparty.proto", &protobuf_RegisterTypes);
  Handle::default_instance_ = new Handle();
  Handle::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_corpc_5fthirdparty_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_corpc_5fthirdparty_2eproto {
  StaticDescriptorInitializer_corpc_5fthirdparty_2eproto() {
    protobuf_AddDesc_corpc_5fthirdparty_2eproto();
  }
} static_descriptor_initializer_corpc_5fthirdparty_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Handle::kHandleFieldNumber;
#endif  // !_MSC_VER

Handle::Handle()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:corpc.thirdparty.Handle)
}

void Handle::InitAsDefaultInstance() {
}

Handle::Handle(const Handle& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:corpc.thirdparty.Handle)
}

void Handle::SharedCtor() {
  _cached_size_ = 0;
  handle_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Handle::~Handle() {
  // @@protoc_insertion_point(destructor:corpc.thirdparty.Handle)
  SharedDtor();
}

void Handle::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Handle::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Handle::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Handle_descriptor_;
}

const Handle& Handle::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_corpc_5fthirdparty_2eproto();
  return *default_instance_;
}

Handle* Handle::default_instance_ = NULL;

Handle* Handle::New() const {
  return new Handle;
}

void Handle::Clear() {
  handle_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Handle::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:corpc.thirdparty.Handle)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 handle = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &handle_)));
          set_has_handle();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:corpc.thirdparty.Handle)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:corpc.thirdparty.Handle)
  return false;
#undef DO_
}

void Handle::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:corpc.thirdparty.Handle)
  // required uint64 handle = 1;
  if (has_handle()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->handle(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:corpc.thirdparty.Handle)
}

::google::protobuf::uint8* Handle::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:corpc.thirdparty.Handle)
  // required uint64 handle = 1;
  if (has_handle()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->handle(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:corpc.thirdparty.Handle)
  return target;
}

int Handle::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint64 handle = 1;
    if (has_handle()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->handle());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Handle::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Handle* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Handle*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Handle::MergeFrom(const Handle& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_handle()) {
      set_handle(from.handle());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Handle::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Handle::CopyFrom(const Handle& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Handle::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void Handle::Swap(Handle* other) {
  if (other != this) {
    std::swap(handle_, other->handle_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Handle::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Handle_descriptor_;
  metadata.reflection = Handle_reflection_;
  return metadata;
}


// ===================================================================

ThirdPartyService::~ThirdPartyService() {}

const ::google::protobuf::ServiceDescriptor* ThirdPartyService::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ThirdPartyService_descriptor_;
}

const ::google::protobuf::ServiceDescriptor* ThirdPartyService::GetDescriptor() {
  protobuf_AssignDescriptorsOnce();
  return ThirdPartyService_descriptor_;
}

void ThirdPartyService::take(::google::protobuf::RpcController* controller,
                         const ::corpc::Void*,
                         ::corpc::thirdparty::Handle*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method take() not implemented.");
  done->Run();
}

void ThirdPartyService::put(::google::protobuf::RpcController* controller,
                         const ::corpc::thirdparty::Handle*,
                         ::corpc::Void*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method put() not implemented.");
  done->Run();
}

void ThirdPartyService::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), ThirdPartyService_descriptor_);
  switch(method->index()) {
    case 0:
      take(controller,
             ::google::protobuf::down_cast<const ::corpc::Void*>(request),
             ::google::protobuf::down_cast< ::corpc::thirdparty::Handle*>(response),
             done);
      break;
    case 1:
      put(controller,
             ::google::protobuf::down_cast<const ::corpc::thirdparty::Handle*>(request),
             ::google::protobuf::down_cast< ::corpc::Void*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& ThirdPartyService::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::corpc::Void::default_instance();
    case 1:
      return ::corpc::thirdparty::Handle::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

const ::google::protobuf::Message& ThirdPartyService::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::corpc::thirdparty::Handle::default_instance();
    case 1:
      return ::corpc::Void::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *reinterpret_cast< ::google::protobuf::Message*>(NULL);
  }
}

ThirdPartyService_Stub::ThirdPartyService_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
ThirdPartyService_Stub::ThirdPartyService_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
ThirdPartyService_Stub::~ThirdPartyService_Stub() {
  if (owns_channel_) delete channel_;
}

void ThirdPartyService_Stub::take(::google::protobuf::RpcController* controller,
                              const ::corpc::Void* request,
                              ::corpc::thirdparty::Handle* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
void ThirdPartyService_Stub::put(::google::protobuf::RpcController* controller,
                              const ::corpc::thirdparty::Handle* request,
                              ::corpc::Void* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)

}  // namespace thirdparty
}  // namespace corpc

// @@protoc_insertion_point(global_scope)
