// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: corpc_option.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "corpc_option.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace corpc {

namespace {


}  // namespace


void protobuf_AssignDesc_corpc_5foption_2eproto() {
  protobuf_AddDesc_corpc_5foption_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "corpc_option.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_corpc_5foption_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_corpc_5foption_2eproto() {
}

void protobuf_AddDesc_corpc_5foption_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fdescriptor_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022corpc_option.proto\022\005corpc\032 google/prot"
    "obuf/descriptor.proto:;\n\021global_service_"
    "id\022\037.google.protobuf.ServiceOptions\030\220N \001"
    "(\r:7\n\016need_coroutine\022\036.google.protobuf.M"
    "ethodOptions\030\222N \001(\010", 179);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "corpc_option.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::ServiceOptions::default_instance(),
    10000, 13, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::MethodOptions::default_instance(),
    10002, 8, false, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_corpc_5foption_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_corpc_5foption_2eproto {
  StaticDescriptorInitializer_corpc_5foption_2eproto() {
    protobuf_AddDesc_corpc_5foption_2eproto();
  }
} static_descriptor_initializer_corpc_5foption_2eproto_;
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint32 >, 13, false >
  global_service_id(kGlobalServiceIdFieldNumber, 0u);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  need_coroutine(kNeedCoroutineFieldNumber, false);

// @@protoc_insertion_point(namespace_scope)

}  // namespace corpc

// @@protoc_insertion_point(global_scope)
